import Link from "next/link";

export const metadata = { title: "Privacy Policy" };

export default function PrivacyPage() {
  return (
    <main className="mx-auto max-w-3xl px-6 py-12 text-sm leading-relaxed text-slate-700">
      <Link href="/" className="text-brand">&larr; Back</Link>
      <h1 className="mt-4 text-3xl font-bold text-slate-900">Privacy Policy</h1>
      <p className="mt-2 text-slate-400">Last updated: {new Date().toISOString().slice(0, 10)}</p>

      <h2 className="mt-8 text-lg font-semibold text-slate-900">What we store</h2>
      <p className="mt-2">
        Creating an account stores your username and a bcrypt hash of your password - never the password
        itself. We do not currently collect an email address, phone number, or payment details.
      </p>
      <p className="mt-2">
        When you generate or attempt a practice set, we store the generated questions, your answers, your
        score, and timestamps, so your history and analysis pages can work. If you add social links (Reddit,
        Instagram, etc.) to your profile, those links are visible to anyone who can view your public profile
        page - only add ones you&apos;re fine sharing.
      </p>

      <h2 className="mt-8 text-lg font-semibold text-slate-900">What we don&apos;t do</h2>
      <p className="mt-2">
        We don&apos;t sell or share your data with third parties, run advertising, or use third-party
        analytics/tracking scripts. There is no email-based password reset because there is no email
        infrastructure - if you forget your password, an admin can reset it for you directly.
      </p>

      <h2 className="mt-8 text-lg font-semibold text-slate-900">Practice content</h2>
      <p className="mt-2">
        Practice questions are generated by a language model and may occasionally be flawed - always
        cross-check anything you&apos;re unsure about rather than treating it as an authoritative source.
      </p>

      <h2 className="mt-8 text-lg font-semibold text-slate-900">Account deletion</h2>
      <p className="mt-2">
        There is currently no self-service account deletion. Contact an admin to have your account and
        associated data removed.
      </p>

      <h2 className="mt-8 text-lg font-semibold text-slate-900">Contact</h2>
      <p className="mt-2">Questions about this policy should go to whoever administers your instance of this app.</p>
    </main>
  );
}
