import Link from "next/link";

export const metadata = { title: "Terms & Conditions" };

export default function TermsPage() {
  return (
    <main className="mx-auto max-w-3xl px-6 py-12 text-sm leading-relaxed text-slate-700">
      <Link href="/" className="text-brand">&larr; Back</Link>
      <h1 className="mt-4 text-3xl font-bold text-slate-900">Terms & Conditions</h1>
      <p className="mt-2 text-slate-400">Last updated: {new Date().toISOString().slice(0, 10)}</p>

      <h2 className="mt-8 text-lg font-semibold text-slate-900">What this is</h2>
      <p className="mt-2">
        This is a practice tool for CAT-style exam preparation. Questions are generated by a language model
        and reviewed by an automated judge, but not by a human subject-matter expert - treat it as practice
        material, not a substitute for official CAT preparation resources or a guarantee of question quality,
        difficulty calibration, or accuracy.
      </p>

      <h2 className="mt-8 text-lg font-semibold text-slate-900">No guarantee of scores or outcomes</h2>
      <p className="mt-2">
        Scores, percentiles, and comparative standing shown here are computed from this app&apos;s own data
        (your attempts and other users&apos; attempts) and are not official CAT percentiles or predictors of
        your actual exam performance.
      </p>

      <h2 className="mt-8 text-lg font-semibold text-slate-900">Your account</h2>
      <p className="mt-2">
        Keep your password private. You&apos;re responsible for activity under your account. Don&apos;t use
        this app to attempt to disrupt the service, scrape it at scale, or abuse the generation pipeline.
      </p>

      <h2 className="mt-8 text-lg font-semibold text-slate-900">Content you add</h2>
      <p className="mt-2">
        Any social links or other profile information you add is visible to other signed-in users via your
        public profile and the leaderboard. Don&apos;t add anything you don&apos;t want shared that way.
      </p>

      <h2 className="mt-8 text-lg font-semibold text-slate-900">No warranty</h2>
      <p className="mt-2">
        This app is provided as-is, without warranty of any kind. It may have bugs, downtime, or generate
        occasionally incorrect questions or answer keys despite the automated judge - report anything that
        looks wrong rather than assuming it&apos;s correct.
      </p>

      <h2 className="mt-8 text-lg font-semibold text-slate-900">Changes</h2>
      <p className="mt-2">These terms may change as the app changes. Continuing to use it after a change means you accept the update.</p>

      <p className="mt-8">
        See also the <Link href="/privacy" className="text-brand">Privacy Policy</Link>.
      </p>
    </main>
  );
}
